#image: n3wtron/maven3-oracle-jdk8

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -DXmx=512m -DXms=1g -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -U"
#  MAVEN_SETTINGS: "<settings><mirrors><mirror><id>telekom</id><mirrorOf>*</mirrorOf><name>Mirror proxy</name><url>http://nexus.services.itc.st.sk:8081/repository/telekom/</url></mirror></mirrors></settings>"
#  SONAR_OPTIONS: "-Dsonar.gitlab.user_token=RLXbVky9Q_ip25tKvTFB  -Dsonar.analysis.mode=preview -Dsonar.gitlab.only_issue_from_commit_line=true -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME"

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - "mvn clean compile $MAVEN_CLI_OPTS -Djacoco.skip=true -DskipTests"
  artifacts:
    paths:
      - target/
      
unit-test-job:
  stage: test
  dependencies:
    - build-job
  script:
    - "mvn package $MAVEN_CLI_OPTS"
  artifacts:
    paths:
      - target/

integration-test-job:
  stage: test
  dependencies:
    - build-job
  script:
    - "mvn verify $MAVEN_CLI_OPTS"
  artifacts:
    paths:
      - target/

deploy-job:
  stage: deploy
  script:
    - "mvn install $MAVEN_CLI_OPTS"
  artifacts:
    paths:
      - "target/*.jar"      
      
      