spring:  
  application:
    name: perf-service
  profiles:
    include: h2, liquibase, microservice
  liquibase:
    change-log: classpath:config/db/changelog/master.xml
    check-change-log-location: true
    drop-first: false
    enabled: true
    #database-change-log-table-name: PERF_CHANGELOG
    #database-change-log-lock-table-name: PERF_CHANGELOG_LCK
  datasource:
    url: jdbc:h2:mem:${spring.application.name};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE    
    continue-on-error: false
    #jdbc:h2:tcp://localhost:9123/~/${spring.application.name};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE    
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none

server:  
  port: ${PORT:2201}